import { c as createComponent, e as createAstro, m as maybeRenderHead, b as addAttribute, a as renderTemplate } from './astro/server_CAqNWn5V.mjs';
import 'kleur/colors';
import 'clsx';

const $$Astro = createAstro();
const $$Thumbnail = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Thumbnail;
  const { title, href, src } = Astro2.props;
  const images = /* #__PURE__ */ Object.assign({"/src/assets/images/creme-fatale1.jpg": () => import('./creme-fatale1_R4LSHMK6.mjs'),"/src/assets/images/creme-fatale2.jpg": () => import('./creme-fatale2_Cpwyjve3.mjs'),"/src/assets/images/creme-fatale3.jpg": () => import('./creme-fatale3_DzwPU0Fi.mjs'),"/src/assets/images/gatita-azul1.jpg": () => import('./gatita-azul1_CNUT2PAi.mjs'),"/src/assets/images/gatita-azul2.jpg": () => import('./gatita-azul2_BNmbmNha.mjs'),"/src/assets/images/gatita-azul3.jpg": () => import('./gatita-azul3_DQlWJHDO.mjs'),"/src/assets/images/home.jpg": () => import('./home_BNNLOJ4Y.mjs'),"/src/assets/images/logo-buenos-mesa.png": () => import('./logo-buenos-mesa_C3fCxQPg.mjs'),"/src/assets/images/logo-cb.png": () => import('./logo-cb_DJlFNNE6.mjs'),"/src/assets/images/logo-che.png": () => import('./logo-che_DH8_b4A5.mjs'),"/src/assets/images/logo-paradise.png": () => import('./logo-paradise_DNkQr7v8.mjs'),"/src/assets/images/logo-solo-paradise.png": () => import('./logo-solo-paradise_CeHYXs5S.mjs'),"/src/assets/images/mi-bella-genio1.jpg": () => import('./mi-bella-genio1_Cm05Qm8C.mjs'),"/src/assets/images/mi-bella-genio2.jpg": () => import('./mi-bella-genio2_DsCr8yiW.mjs'),"/src/assets/images/mi-bella-genio3.jpg": () => import('./mi-bella-genio3_CxrNbVZl.mjs'),"/src/assets/images/poison-blue1.jpg": () => import('./poison-blue1_Bn7sB93z.mjs'),"/src/assets/images/poison-blue2.jpg": () => import('./poison-blue2_B6qMlCWF.mjs'),"/src/assets/images/poison-blue3.jpg": () => import('./poison-blue3_Y43cE2Ac.mjs'),"/src/assets/images/quien-soy1.jpg": () => import('./quien-soy1_DrYsd0c4.mjs'),"/src/assets/images/quien-soy2.jpg": () => import('./quien-soy2_F08uYLkl.mjs'),"/src/assets/images/renaissance1.jpg": () => import('./renaissance1_Dvtsr8wu.mjs'),"/src/assets/images/renaissance2.jpg": () => import('./renaissance2_C956XxWo.mjs'),"/src/assets/images/renaissance3.jpg": () => import('./renaissance3_CmKlhOkh.mjs'),"/src/assets/images/show-creme-fatale.jpg": () => import('./show-creme-fatale_BmzmLJov.mjs'),"/src/assets/images/show-gatita-azul.jpg": () => import('./show-gatita-azul_FdjWg_8u.mjs'),"/src/assets/images/show-renaissance.jpg": () => import('./show-renaissance_DlhMtgJP.mjs'),"/src/assets/images/testimonios.jpg": () => import('./testimonios_BJFApaoQ.mjs'),"/src/assets/images/tren-nocturno1.jpg": () => import('./tren-nocturno1_9wtb7y4b.mjs'),"/src/assets/images/tren-nocturno2.jpg": () => import('./tren-nocturno2_pdRvPZyJ.mjs'),"/src/assets/images/tren-nocturno3.jpg": () => import('./tren-nocturno3_BbDf7CkT.mjs'),"/src/assets/images/tren-nocturno4.jpg": () => import('./tren-nocturno4_dEG5BHdW.mjs'),"/src/assets/images/tren-nocturno5.jpg": () => import('./tren-nocturno5_DYN1hZM3.mjs')});
  const img = await images["/src/assets/images/" + src]();
  return renderTemplate`${maybeRenderHead()}<div class="lg:w-[30vw] flex-[0_0_auto] mb-2"> <a${addAttribute(href, "href")}> <p class="text-center uppercase font-sans font-medium mb-2">${title}</p> <img${addAttribute(img.default.src, "src")} class="w-[90vw] lg:w-[100%] [aspect-ratio:1.5] [object-fit:cover] cursor-pointer"${addAttribute(href ? "" : `showModal('<img class="w-[100%]" src=${img.default.src} />')`, "onclick")}> </a> </div>`;
}, "/Users/miguel/Development/astro-demo/src/components/Thumbnail.astro", void 0);

export { $$Thumbnail as $ };
